lib/plangora_web/router.ex
defmodule PlangoraWeb.Router do
  use PlangoraWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PlangoraWeb.MaybeAuth
    plug PlangoraWeb.Locale
    plug PlangoraWeb.GoogleAnalytics
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin_section do
    plug PlangoraWeb.AdminAuth
    plug :put_layout, {PlangoraWeb.LayoutView, :admin}
  end

  pipeline :user_section do
    plug PlangoraWeb.UserAuth
  end

  scope "/", PlangoraWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/contact", PageController, :new
    get "/register", UserController, :new

    resources "/users", UserController, only: [:create]
    resources "/news-posts", NewsPostController, param: "slug", only: [:show, :index]
    resources "/video-posts", VideoPostController, param: "slug", only: [:show, :index]
    resources "/video-categories", VideoCategoryController, param: "category_slug", only: [:show]

    resources "/user-sessions", UserSessionController, only: [:create]
    get "/login", UserSessionController, :new
    delete "/logout", UserSessionController, :delete

    get "/admin-login", AdminSessionController, :new
    resources "/admin-sessions", AdminSessionController, only: [:delete, :create], singleton: true

    scope "/plangora_admin" do
      pipe_through [:admin_section]

      resources "/users", AdminController, except: [:update]
      resources "/video-posts", AdminVideoPostController
      resources "/video-categories", VideoCategoryController
      resources "/news-posts", AdminNewsPostController
      resources "/leads", LeadsController, only: [:index, :show, :delete]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", PlangoraWeb do
  #   pipe_through :api
  # end
end

lib/plangora/multimedia/video_post.ex
defmodule Plangora.Multimedia.VideoPost do
  use Ecto.Schema
  import Ecto.Changeset
  import Ecto.Query, only: [from: 2]

  alias Plangora.Accounts.Admin
  alias Plangora.Multimedia.VideoCategory

  @video_regex ~r/\Ahttps?:\/\/(?:www\.)?(?:youtu\.be|youtube\.com)\/(?:watch\?v=)*(?<youtube_id>[a-zA-Z0-9_-]{11})?/
  # @youtube_thumbnail_regex ~r/\Ahttps?:\/\/(?:www\.img\.youtube\.com)\/(?:vi)\/*(?<vid>[a-zA-Z0-9_-]{11})\/(?:maxresdefault\.jpg)?/
  @slug_regex ~r/^[a-zA-Z0-9-]+$/

  schema "video_posts" do
    field :description, :string
    field :slug, :string
    field :title, :string
    field :url, :string
    field :is_deleted, :boolean, default: false
    field :zh_title, :string
    field :zh_description, :string

    belongs_to(:admin, Admin)
    belongs_to(:category, VideoCategory)

    timestamps()
  end

  @required_attributes [
    :description,
    :title,
    :url,
    :slug,
    :is_deleted,
    :category_id
  ]

  @cast_attributes [
    :description,
    :title,
    :url,
    :slug,
    :is_deleted,
    :category_id,
    :zh_title,
    :zh_description
  ]

  @doc false
  def changeset(video_post, attrs) do
    video_post
    |> cast(attrs, @cast_attributes)
    |> generate_slug()
    |> validate_required(@required_attributes)
    |> validate_length(:title, max: 255, message: "should be at most %{count} characters")
    |> validate_format(:slug, @slug_regex,
      message: "Slug should be unique and No SPACE or @#$%^&*()+=: should be used."
    )
    |> validate_format(:url, @video_regex, message: "Invalid YouTube link")
    |> unique_constraint(:slug)
  end

  def create_changeset(video_post, attrs) do
    changeset(video_post, attrs)
  end

  def delete_changeset(video_post, attrs) do
    video_post
    |> cast(attrs, [:is_deleted])
  end

  def search(query, search_term) do
    wildcard_search = "%#{search_term}%"

    from video_post in query,
      where: ilike(video_post.title, ^wildcard_search),
      or_where: ilike(video_post.description, ^wildcard_search)
  end

  def generate_slug(%Ecto.Changeset{} = changeset) do
    slug = get_field(changeset, :slug)
    title = get_field(changeset, :title)

    cond do
      not is_nil(slug) ->
        change(changeset, slug: slug)

      is_nil(slug) and not is_nil(title) ->
        change(changeset, slug: Slug.slugify(title))

      true ->
        changeset
    end
  end

  def video_regex, do: @video_regex
end

lib/plangora_web/controllers/video_post_controller.ex
defmodule PlangoraWeb.VideoPostController do
  use PlangoraWeb, :controller

  alias Plangora.Multimedia

  def index(conn, params) do
    video_posts = Multimedia.list_video_posts(params)
    render(conn, "index.html", video_posts: video_posts)
  end

  def show(conn, %{"slug" => slug}) do
    video_post = Multimedia.get_video_post_by_slug(slug)
    render(conn, "show.html", video_post: video_post)
  end
end

lib/plangora_web/views/video_post_view.ex
defmodule PlangoraWeb.VideoPostView do
  use PlangoraWeb, :view

  alias Plangora.Multimedia.VideoPost

  def render_youtube_thumbnail(link) do
    case Regex.named_captures(VideoPost.video_regex(), link) do
      %{"youtube_id" => youtube_id} ->
        render_youtube_thumbnail_html(
          "https://img.youtube.com/vi/" <> youtube_id <> "/maxresdefault.jpg"
        )
    end
  end

  defp render_youtube_thumbnail_html(video_link),
    do: img_tag(video_link, height: "70%", width: "60%")

  def render_youtube_video(link) do
    case Regex.named_captures(VideoPost.video_regex(), link) do
      %{"youtube_id" => youtube_id} ->
        render_embed_video_html("https://www.youtube.com/embed/" <> youtube_id)
    end
  end

  defp render_embed_video_html(video_link),
    do: {:safe, ~s(<iframe class="embed-responsive-item" src="#{video_link}"
        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen></iframe>)}

  def render_translation(en, nil, _locale), do: en
  def render_translation(_en, zh, "zh"), do: zh
  def render_translation(en, _zh, _locale), do: en
end

lib/plangora_web/templates/video_post/index.html.eex
<div class="d-flex justify-content-center mt-4 mb-4">
    <div class="d-inline-flex p-2 bd-highligh">
        <%= button gettext("All"), to: Routes.video_post_path(@conn, :index), method: :get, class: "btn btn-outline-danger" %>
    </div>
    <div class="d-inline-flex p-2 bd-highligh">
        <%= button "Phoenix", to: Routes.video_category_path(@conn, :show, "phoenix"), method: :get, class: "btn btn-outline-danger" %>
    </div>
    <div class="d-inline-flex p-2 bd-highligh">
        <%= button "Elixir", to: Routes.video_category_path(@conn, :show, "elixir"), method: :get, class: "btn btn-outline-danger" %>
    </div>
    <div class="d-inline-flex p-2 bd-highligh">
        <%= button "Live View", to: Routes.video_category_path(@conn, :show, "live-view"), method: :get, class: "btn btn-outline-danger" %>
    </div>
</div>

<div class="col-md-6 offset-md-3 mt-2 mb-4 border border-success pt-3">
    <%= form_for @conn, Routes.video_post_path(@conn, :index), [method: :get], fn f -> %>
    <div class="input-group mb-3">
        <%= search_input f, :query, placeholder: gettext("Search Video"), class: "form-control" %>
        <div class="input-group-append">
            <%= submit gettext("Search"), class: "btn btn-outline-success  my-sm-0" %>
        </div>
    </div>
    <% end %>
</div>

<div class="container">
    <div class="text-center mb-3">
        <h1><%= gettext("Videos") %></h1>
    </div>

    <div class="row">
        <%= for video <- @video_posts do %>
        <div class="col-12 col-md-4">
            <div class="card border-primary mb-5 ml-1 mr-1 text-center" style="width: 20rem;">
                <div class="card-body">
                    <h5 class="card-title">
                        <%= render_translation(video.title, video.zh_title, @locale) %>
                    </h5>
                    <p class="card-text">
                        <%= render_youtube_thumbnail(video.url) %>
                    </p>
                    <%= link(gettext("Watch Video"), to: Routes.video_post_path(@conn, :show, video.slug), class: "btn btn-outline-primary my-2 my-sm-0") %>
                </div>
            </div>
        </div>
        <% end %>
    </div>
</div>

lib/plangora_web/templates/video_post/show.html.eex
<h1 class="text-center mt-2 mb-4">
    <%= render_translation(@video_post.title, @video_post.zh_title, @locale) %>
</h1>

<div style="text-align:center">
    <div class="embed-responsive embed-responsive-16by9">
        <%= render_youtube_video(@video_post.url) %>
    </div>
</div>

<h6 class="mt-2 mb-4">
    <%= gettext("Description") %>:
</h6>
<p class="text-justify text-sm-left font-weight-light">
    <%= render_translation(@video_post.description, @video_post.zh_description, @locale) %>
</p>