lib/plangora_web/router.ex
defmodule PlangoraWeb.Router do
  use PlangoraWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PlangoraWeb.MaybeAuth
    plug PlangoraWeb.Locale
    plug PlangoraWeb.GoogleAnalytics
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin_section do
    plug PlangoraWeb.AdminAuth
    plug :put_layout, {PlangoraWeb.LayoutView, :admin}
  end

  pipeline :user_section do
    plug PlangoraWeb.UserAuth
  end

  scope "/", PlangoraWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/contact", PageController, :new
    get "/register", UserController, :new

    resources "/users", UserController, only: [:create]
    resources "/news-posts", NewsPostController, param: "slug", only: [:show, :index]
    resources "/video-posts", VideoPostController, param: "slug", only: [:show, :index]
    resources "/video-categories", VideoCategoryController, param: "category_slug", only: [:show]

    resources "/user-sessions", UserSessionController, only: [:create]
    get "/login", UserSessionController, :new
    delete "/logout", UserSessionController, :delete

    get "/admin-login", AdminSessionController, :new
    resources "/admin-sessions", AdminSessionController, only: [:delete, :create], singleton: true

    scope "/plangora_admin" do
      pipe_through [:admin_section]

      resources "/users", AdminController, except: [:update]
      resources "/video-posts", AdminVideoPostController
      resources "/video-categories", VideoCategoryController
      resources "/news-posts", AdminNewsPostController
      resources "/leads", LeadsController, only: [:index, :show, :delete]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", PlangoraWeb do
  #   pipe_through :api
  # end
end

lib/plangora_web/controllers/admin_panel/admin_video_post_controller.ex
defmodule PlangoraWeb.AdminVideoPostController do
  use PlangoraWeb, :controller

  alias Plangora.Multimedia
  alias Plangora.Multimedia.VideoPost

  plug :load_category_options when action in [:new, :create, :edit, :update]

  defp load_category_options(conn, _) do
    assign(conn, :video_category_options, Multimedia.list_video_category_options())
  end

  def index(conn, params) do
    video_posts = Multimedia.list_video_posts(params)
    render(conn, "index.html", video_posts: video_posts)
  end

  def new(conn, _params) do
    changeset = Multimedia.change_video_post(%VideoPost{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(%{assigns: %{current_admin: %{id: admin_id}}} = conn, %{
        "video_post" => video_post_params
      }) do
    case Multimedia.create_video_post(video_post_params, admin_id) do
      {:ok, video_post} ->
        conn
        |> put_flash(:info, "Video post created successfully.")
        |> redirect(to: Routes.admin_video_post_path(conn, :show, video_post))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(
          :error,
          "There was an error while creating the video, please fix and try again"
        )
        |> render("new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    video_post = Multimedia.get_video_post!(id)
    render(conn, "show.html", video_post: video_post)
  end

  def edit(conn, %{"id" => id}) do
    video_post = Multimedia.get_video_post!(id)
    changeset = Multimedia.change_video_post(video_post)

    render(conn, "edit.html",
      video_post: video_post,
      changeset: changeset
    )
  end

  def update(conn, %{"id" => id, "video_post" => video_post_params}) do
    video_post = Multimedia.get_video_post!(id)

    case Multimedia.update_video_post(video_post, video_post_params) do
      {:ok, video_post} ->
        conn
        |> put_flash(:info, "Video post updated successfully.")
        |> redirect(to: Routes.admin_video_post_path(conn, :show, video_post))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html",
          video_post: video_post,
          changeset: changeset
        )
    end
  end

  def delete(conn, %{"id" => id}) do
    video_post = Multimedia.get_video_post!(id)
    {:ok, _video_post} = Multimedia.delete_video_post(video_post)

    conn
    |> put_flash(:info, "Video post deleted successfully.")
    |> redirect(to: Routes.admin_video_post_path(conn, :index))
  end
end

lib/plangora_web/views/admin_panel/admin_video_post_view.ex
defmodule PlangoraWeb.AdminVideoPostView do
  use PlangoraWeb, :view
end

lib/plangora_web/templates/admin_video_post/edit.html.eex
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <h1>Edit Video</h1>

        <%= form_for @changeset, Routes.admin_video_post_path(@conn, :update, @video_post), fn f -> %>

        <div class="form-group">
            <%= label f, :title, "Title" %>
            <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
            <%= error_tag(f, :title) %>
        </div>

        <div class="form-group">
            <%= label f, :description, "Description" %>
            <%= textarea f, :description, placeholder: "Description", class: "form-control" %>
            <%= error_tag(f, :description) %>
        </div>

        <div class="form-group">
            <%= label f, :zh_description, "Chinese Description" %>
            <%= textarea f, :zh_description, placeholder: "Chinese Description", class: "form-control" %>
             <%= error_tag(f, :zh_description) %>
        </div>

        <div class="form-group">
            <%= label f, :url, "Link: " %>
            <%= text_input f, :url, placeholder: "Link", class: "form-control" %>
            <%= error_tag(f, :url) %>
        </div>

        <div class="form-group">
            <%= label f, :slug, "Slug" %>
            <%= text_input f, :slug, placeholder: "Slug", class: "form-control" %>
            <%= error_tag(f, :slug) %>
        </div>

        <div class="form-group">
            <%= label f, :category_id, "Category" %>
            <%= select f, :category_id, @video_category_options, class: "form-control" %>
        </div>

        <div class="form-actions">
            <%= submit "Update Video" %>
        </div>

        <div class="link d-flex flex-row-reverse bd-highlight">
            <%= link "Back", to: Routes.admin_video_post_path(@conn, :show, @video_post.id) %> 
        </div> 

        <% end %>
    </div>
</div>

lib/plangora_web/templates/admin_video_post/index.html.eex
<div class="text-center">
<h1>Listing All Video</h1>
</div>

<%= link "Upload New Video", to: Routes.admin_video_post_path(@conn, :new) %><br>
<%= link "Create Video Category", to: Routes.video_category_path(@conn, :new) %><br>
<%= link "All Video Categories", to: Routes.video_category_path(@conn, :index) %><br>
<%= link "All", to: Routes.admin_video_post_path(@conn, :index) %>

<div class="d-flex flex-row-reverse bd-highlight">
    <%= form_for @conn, Routes.admin_video_post_path(@conn, :index), [method: :get, class: "pull-right"], fn f -> %>
    <%= search_input f, :query %>
    <%= submit "Search" %>
    <% end %>
</div>
<div class="container mb-5 mt-3">
    <table id="videodata"
        class="table table-hover table-bordered videodata" 
        style="width: 100%" >

        <thead>
            <tr>
            <th><b>TITLE</b></th>
            <th><b> SLUG</b> </th>
            <th><b> </b> </th>
            </tr>
        </thead>
        <tbody>
            <%= for video <- @video_posts do %>
            <tr>
                <th><%= video.title %> </th>
            
                <th><%= video.slug %> </th>
                
                <th><%= link "View", to: Routes.admin_video_post_path(@conn, :show, video.id) %> </th>

            </tr>
            <% end %>
        </tbody>
            
        <tfoot>
            <tr>
            <th><b>TITLE</b></th>
            <th><b> SLUG</b> </th>
            <th><b> </b> </th>
            </tr>
        </tfoot>   
    </table>
</div>

<%= link "Log out", to: Routes.admin_session_path(@conn, :delete), method: :delete %>

lib/plangora_web/templates/admin_video_post/new.html.eex
<%= if @changeset.action do %>
    <div class="alert alert-danger">
        <p>Something's wrong!</p>
    </div>
<% end %>

<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
    <h1>Create Video </h1>
    <%= form_for @changeset, Routes.admin_video_post_path(@conn, :create), fn f -> %>

        <div class="form-group">
            <%= label f, :title, "Title" %>
            <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
            <%= error_tag(f, :title) %>
        </div>

        <div class="form-group">
            <%= label f, :description, "Description" %>
            <%= textarea f, :description, placeholder: "Description", class: "form-control" %>
            <%= error_tag(f, :description) %>
        </div>

        <div class="form-group">
            <%= label f, :zh_description, "Chinese Description" %>
            <%= textarea f, :zh_description, placeholder: "Chinese Description", class: "form-control" %>
            <%= error_tag(f, :zh_description) %>
        </div>

        <div class="form-group">
            <%= label f, :url, "Link" %>
            <%= text_input f, :url, placeholder: "Link", class: "form-control" %>
            <%= error_tag(f, :url) %>
        </div>

        <div class="form-group">
            <%= label f, :slug, "Slug" %>
            <%= text_input f, :slug, placeholder: "Slug", class: "form-control" %>
            <%= error_tag(f, :slug) %>
        </div>
        <div class="form-group">
            <%= label f, :category_id, "Category" %>
            <%= select f, :category_id, @video_category_options, class: "form-control" %>
        </div>

        <div class="form-actions">
        <%= submit "Create New Video" %>
        </div>

        <div class="link">
            <%= link "Back", to: Routes.admin_video_post_path(@conn, :index) %> 
        </div> 
        <% end %>
    </div>
</div>

lib/plangora_web/templates/admin_video_post/show.html.eex
<div class="row">
    <div class="col-12">
        <h1> <%= @video_post.title %> </h1>
        <%= form_for @conn, Routes.admin_video_post_path(@conn, :show, @video_post), fn _f -> %>

        <table class="table table-hover">
            <tbody>
                <tr>
                    <td> Description </td>
                    <td> <%= @video_post.description %> </td>
                </tr>
                <tr>
                    <td> Chinese Description </td>
                    <td> <%= @video_post.zh_description %> </td>
                </tr>
                <tr>
                    <td> Link </td>
                    <td> <%= link @video_post.url, to: @video_post.url %> </td>
                </tr>
                <tr>
                    <td> Slug </td>
                    <td> <%= @video_post.slug %> </td>
                </tr>
                <tr>
                    <td> Category </td>
                    <td> <%= @video_post.category.title %> </td>
                </tr>
            </tbody>
        </table>
        <% end %>

        <div class="d-flex justify-content-around">
            <%= link "Add", to: Routes.admin_video_post_path(@conn, :new) %>
            <%= link "Edit", to: Routes.admin_video_post_path(@conn, :edit, @video_post.id) %>
            <%= link "Delete", to: Routes.admin_video_post_path(@conn, :delete, @video_post), method: :delete, data: [confirm: "Are you sure?"] %>
            <%= link "Back", to: Routes.admin_video_post_path(@conn, :index) %>
        </div>
    </div>
</div>