lib/plangora_web/router.ex
defmodule PlangoraWeb.Router do
  use PlangoraWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PlangoraWeb.MaybeAuth
    plug PlangoraWeb.Locale
    plug PlangoraWeb.GoogleAnalytics
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin_section do
    plug PlangoraWeb.AdminAuth
    plug :put_layout, {PlangoraWeb.LayoutView, :admin}
  end

  pipeline :user_section do
    plug PlangoraWeb.UserAuth
  end

  scope "/", PlangoraWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/contact", PageController, :new
    get "/register", UserController, :new

    resources "/users", UserController, only: [:create]
    resources "/news-posts", NewsPostController, param: "slug", only: [:show, :index]
    resources "/video-posts", VideoPostController, param: "slug", only: [:show, :index]
    resources "/video-categories", VideoCategoryController, param: "category_slug", only: [:show]

    resources "/user-sessions", UserSessionController, only: [:create]
    get "/login", UserSessionController, :new
    delete "/logout", UserSessionController, :delete

    get "/admin-login", AdminSessionController, :new
    resources "/admin-sessions", AdminSessionController, only: [:delete, :create], singleton: true

    scope "/plangora_admin" do
      pipe_through [:admin_section]

      resources "/users", AdminController, except: [:update]
      resources "/video-posts", AdminVideoPostController
      resources "/video-categories", VideoCategoryController
      resources "/news-posts", AdminNewsPostController
      resources "/leads", LeadsController, only: [:index, :show, :delete]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", PlangoraWeb do
  #   pipe_through :api
  # end
end

lib/plangora/accounts/user.ex
defmodule Plangora.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :name, :string
    field :email, :string
    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true
    field :password_hash, :string
    field :is_active, :boolean, default: true

    timestamps()
  end

  @required_attributes [
    :email,
    :name,
    :is_active,
    :password,
    :password_confirmation
  ]

  @allowed_attributes [
    :name,
    :is_active,
    :password,
    :password_confirmation
  ]

  def changeset(user, attrs) do
    user
    |> cast(attrs, @allowed_attributes)
    |> email_changeset(attrs)
    |> validate_length(:password, min: 8, message: "must be at least %{count} characters")
    |> validate_confirmation(:password, message: "does not match password")
    |> put_pass_hash()
  end

  def email_changeset(user, attrs) do
    user
    |> cast(attrs, [:email])
    |> validate_format(:email, ~r/\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
      message: "must be an email"
    )
    |> validate_required([:email])
    |> unique_constraint(:email)
  end

  def register_changeset(user, attrs) do
    changeset(user, attrs)
    |> validate_required(@required_attributes)
  end

  def update_changeset(user, attrs) do
    changeset(user, attrs)
    |> validate_required([:password])
  end

  def delete_changeset(user, attrs) do
    user
    |> cast(attrs, [:is_active])
  end

  defp put_pass_hash(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: pass}} when is_binary(pass) ->
        put_change(changeset, :password_hash, Bcrypt.hash_pwd_salt(pass))

      _ ->
        changeset
    end
  end
end

lib/plangora_web/controllers/user_controller.ex
defmodule PlangoraWeb.UserController do
  use PlangoraWeb, :controller
  alias Plangora.Accounts
  alias Plangora.Accounts.User
  alias PlangoraWeb.UserAuth

  def new(conn, _params), do: render(conn, "new.html", changeset: Accounts.change_user(%User{}))

  def create(conn, %{"user" => user_params}) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> UserAuth.login(user)
        |> put_flash(:info, gettext("Sign up successful!"))
        |> redirect(to: Routes.video_post_path(conn, :index))

      {:error, changeset} ->
        conn
        |> put_flash(
          :error,
          gettext("There was an error while signing up, please fix and try again")
        )
        |> render("new.html", changeset: changeset)
    end
  end
end

lib/plangora_web/views/user_view.ex
defmodule PlangoraWeb.UserView do
  use PlangoraWeb, :view
end

lib/plangora_web/templates/user/new.html.eex
<%= if @changeset.action do %>
    <div class="alert alert-danger">
        <p>gettext("Something's wrong!")</p>
    </div>
<% end %>

<div class="row">
  <div class="col-12 col-md-6 offset-md-3">
    <h1><%= gettext("Registration") %></h1>
    <%= form_for @changeset, Routes.user_path(@conn, :create), [as: :user], fn f -> %>

        <div class="form-group">
          <%= label f, :email, gettext("Email") %>
          <%= text_input f, :email, required: true, placeholder: gettext("Email Address"), class: "form-control" %>
          <%= error_tag(f, :email) %>
        </div>
        <div class="form-group">
          <%= label f, :name, gettext("Name") %>
          <%= text_input f, :name, required: true, placeholder: gettext("Name"), class: "form-control" %>
          <%= error_tag(f, :name) %>
        </div>
        <div class="form-group">
          <%= label f, :password, gettext("Password") %>
          <%= password_input f, :password, required: true, placeholder: gettext("Password"), class: "form-control" %>
          <%= error_tag(f, :password) %>
        </div>
        <div class="form-group">
          <%= label f, :password_confirmation, gettext("Confirm Password") %>
          <%= password_input f, :password_confirmation, required: true, placeholder: gettext("Retype password"), class: "form-control" %>
          <%= error_tag(f, :password_confirmation) %>
        </div>

        <div class="form-actions">
            <%= submit gettext("Create Account") %>
        </div>
    <% end %>
  </div>
</div>