lib/plangora_web/router.ex
defmodule PlangoraWeb.Router do
  use PlangoraWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PlangoraWeb.MaybeAuth
    plug PlangoraWeb.Locale
    plug PlangoraWeb.GoogleAnalytics
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admin_section do
    plug PlangoraWeb.AdminAuth
    plug :put_layout, {PlangoraWeb.LayoutView, :admin}
  end

  pipeline :user_section do
    plug PlangoraWeb.UserAuth
  end

  scope "/", PlangoraWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/contact", PageController, :new
    get "/register", UserController, :new

    resources "/users", UserController, only: [:create]
    resources "/news-posts", NewsPostController, param: "slug", only: [:show, :index]
    resources "/video-posts", VideoPostController, param: "slug", only: [:show, :index]
    resources "/video-categories", VideoCategoryController, param: "category_slug", only: [:show]

    resources "/user-sessions", UserSessionController, only: [:create]
    get "/login", UserSessionController, :new
    delete "/logout", UserSessionController, :delete

    get "/admin-login", AdminSessionController, :new
    resources "/admin-sessions", AdminSessionController, only: [:delete, :create], singleton: true

    scope "/plangora_admin" do
      pipe_through [:admin_section]

      resources "/users", AdminController, except: [:update]
      resources "/video-posts", AdminVideoPostController
      resources "/video-categories", VideoCategoryController
      resources "/news-posts", AdminNewsPostController
      resources "/leads", LeadsController, only: [:index, :show, :delete]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", PlangoraWeb do
  #   pipe_through :api
  # end
end

lib/plangora_web/views/layout_view.ex
defmodule PlangoraWeb.LayoutView do
  use PlangoraWeb, :view
end

lib/plangora_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Plangora Limited - Admin Panel</title>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
  <%= csrf_meta_tag() %>
</head>

<body>
  <header id="header">
    <%= img_tag(Routes.static_path(@conn, "/images/logo.jpg"), class: "logo", height: "60%", width: "50%") %>
  </header>
  <main role="main" class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Plangora</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

          <li class="nav-item">
            <div class="nav-link">
              <%= link gettext("Home"), to: Routes.video_post_path(@conn, :index), class: "text-secondary" %>
            </div>
          </li>
          <li class="nav-item">
            <div class="nav-link">
              <%= link gettext("Video"), to: Routes.admin_video_post_path(@conn, :index), class: "text-secondary" %>
            </div>
          </li>
          <li class="nav-item">
            <div class="nav-link">
              <%= link gettext("News"), to: Routes.admin_news_post_path(@conn, :index), class: "text-secondary" %>
            </div>
          </li>
          <li class="nav-item">
            <div class="nav-link">
              <%= link gettext("Message"), to: Routes.leads_path(@conn, :index), class: "text-secondary" %>
            </div>
          </li>
        </ul>
      </div>
    </nav>

    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <%= render @view_module, @view_template, assigns %>

    <footer>
      <div>
        <p class="sticky-bottom text-right font-italic">
          © 2020 Plangora Limited
        </p>
      </div>
    </footer>

  </main>
  <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</body>

</html>

lib/plangora_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Plangora Limited</title>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <%= csrf_meta_tag() %>
</head>

<body>

  <header id="header">
    <%= img_tag(Routes.static_path(@conn, "/images/logo.jpg"), class: "logo", height: "60%", width: "50%") %>
  </header>
  <main role="main" class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-white border border-warning">
      <a class="navbar-brand text-dark" style="font-size: 30px" href="#">Plangora</a>
      <button class="navbar-toggler border border-warning" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active mx-3">
            <%= link gettext("Home"), to: Routes.page_path(@conn, :index), class: "text-dark nav-link" %>
          </li>
          <li class="nav-item mx-3">
            <%= link gettext("Video"), to: Routes.video_post_path(@conn, :index), class: "text-dark nav-link" %>
          </li>
          <li class="nav-item mx-3">
            <%= link gettext("News"), to: Routes.news_post_path(@conn, :index), class: "text-dark nav-link" %>
          </li>
          <li class="nav-item mx-3">
            <%= link gettext("Contact"), to: Routes.page_path(@conn, :new), class: "text-dark nav-link" %>
          </li>
          <li class="nav-item dropdown mx-3">
            <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= gettext("Language") %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="?locale=en">EN</a>
              <a class="dropdown-item" href="?locale=zh">中文</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>

    <p class="alert alert-info col-11" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger col-11" role="alert"><%= get_flash(@conn, :error) %></p>

    <%= render @view_module, @view_template, assigns %>

    <footer>
      <div class="sticky-bottom">
        <div class="text-right font-italic">
          <%= link img_tag(Routes.static_path(@conn, "/images/digital_ocean.jpeg"), class: "img-fluid do-img"), to: "https://m.do.co/c/b880985e5d50" %>
          © 2020 Plangora Limited
        </div>
      </div>
    </footer>
  </main>

  <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  <%= if assigns[:google_analytics_id] do %>
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%= @google_analytics_id %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', '<%= @google_analytics_id %>');
  </script>
  <% end %>
</body>

</html>